[package]
name = "store-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.sqlx]
version = "0.7.2"
features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid"]
