// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCause } from "./ErrorCause";

export type ApiError = { reason: ErrorCause, message: string, };
